[project]
name = "pathblockerai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "plotly>=6.0.1",
    "pygame>=2.6.1",
    "torch>=2.7.0",
]
