

class Env:

    def step(self, action):
        """
        Applies an action to the environment.

        Parameters:
        - action: The action to be taken

        Return:
        tuple[state, reward, terminated] 
        - state: The updated observed state
        - reward: The reward generated by the action
        - terminated: True if the environment has reached it's terminal state
        """
        ...

    def reset(self, seed: int = 1738):
        """
        Resets the environment to an initial state. 

        Parameters:
        - seed: Seed for randomization (optional)

        Returns:
        - observation: Initial observation of new environment
        """
        ...

    def close(self):
        """
        Cleans up the environment

        Parameters:
        None

        Returns:
        None
        """
        ...

    @property
    def action_space(self):
        """
        Returns the possible actions from the current state
        """
        return []

    @property 
    def observation_space(self):
        """
        Returns the space of possible observations
        """
        return []
